version: "3.8"
services:
    todolist:
        build: .
        deploy:
            replicas: 3
        labels:
            - "traefik.http.routers.todolist.rule=PathPrefix(`/api/todo`)"
            - "traefik.http.middlewares.todolist.stripprefix.forceSlash=false"
            - "traefik.http.routers.todolist.middlewares=todolist@docker"

    traefik:
        image: traefik:latest
        restart: unless-stopped
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.toml:/traefik.toml

    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: example
